name: call_me

on:
    workflow_dispatch:
    schedule:
      - cron: '15 8 * * *'
jobs:
    build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
  
      - name: Get date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
  
      - name: Run exe
        id: run
        shell: bash
        run: |
          ./dist/master.exe > output.txt
          result=$(cat output.txt)  # 使用 base64 编码
          echo "result<<EOF" >> $GITHUB_ENV  # 使用特殊的语法
          echo "$result" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Test mail from GitHub Actions ${{ env.DATE }}
          to: uu3fusy@outlook.com,yangjb01@163.com
          from: 3401477225@qq.com
          body: ${{ env.result }}
          content_type: text/plain